### ISSUE TITLE
Shouldn't ZIO implementation be a separate project?

### ISSUE THREAD

**Issue by Lanayx** [AnthonyLloyd/Fsion#3]
Hi! I'm very excited by your article about zio implementation, would like to see it as a separate project, do you have any plans for that?

**Comment by AnthonyLloyd** [comment]
Yes. Its just here to incubate it a little. I'm working on FileService, IO.throttle & IO.fold at the moment. Will consider moving to a separate project and then a separate repo in 1-2 weeks.
