### ISSUE TITLE
Correct Bind overload could not be determined

### ISSUE THREAD

**Issue by isaacabraham** [AnthonyLloyd/Fsion#4]
Changing the test sample to the following results in an error:

```fsharp
let program() =
    io {
        let! name = Console.readLine()
        let! blah = Console.readLine()
        return 0
    }
```

```
A unique overload for method 'Bind' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: member IOBuilder.Bind : io:IO<'r,'a,'e1> * f:('a -> IO<'r,'b,'e2>) -> IO<'r,'b,Choice<'e1,'e2>>, member IOBuilder.Bind : io:IO<'r,'a,'e> * f:('a -> IO<'r,'b,'e>) -> IO<'r,'b,'e>
```

Why does this happen?

**Comment by AnthonyLloyd** [comment]
The auto raise of error is not working. I'm not sure if it ever did fully or I've changed it. Will check. I've see this error recently when trying to use rec functions.

Not such an issue to remove this and require this to be done manually. I think ZIO requires this.

STRP seems to be able to do this correctly outside a CE. Maybe it's possible or something to raise.

**Comment by AnthonyLloyd** [comment]
I've removed the error auto lift to choice. It can't be made to work in all cases. Doing this manually isn't such an issue.

Maybe CEs could get a bit more power in future to be able to do this sort of thing.
